server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  application:
    name: configserver
  security:
    user:
      password: '{cipher}AQB8qfjYm4C9MqbK9KjaMlwbbyfx697kyTtWuahlbP2rl/b2b/5z4pErdtQP3Hb2KD2trn+AWMf5XMuVKOCBU/vtys2ROgg3BwAEFEa697aZUAkSO/IsFqRBevFEWaQC7XgNOiENQ0X8SITDE7Mjo/QKHSdV8kjvnuHhIhdm+K5nXFmJ/RexChrb3SfDJjAUkaCMFJCGA3zJH2uATXHCLxCYDORqE/TRG1FijjFiEGZR+YJpDc5yi9u4Teht5xBvxZ6x9T2Hm5Kmtz1Ko2vk+epz1F5vS5mCBohUrfwmLMMGl53FF8jakdFlxiDPQfbx6xZX9lp95vnbtQsP+ASyzLUNzkFRptMAMNHfpJODAB6WwLeRoxgD+Ia5eQU6uwmaLCQ='
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/maximilianwollnik/config-repo
          username: maximilianwollnik
          password: '{cipher}AQA+rZXNEXsxPNpn3DKy3jfnoAhAtnPwe1pc0VHr0TJT9Wl1cG4fBgh6XT+69TGHTH+vFisuUum/dmoe/9oF9YhWS8KlcmJSQLd0GDz0R6BylZCAvjvUAInEPZgDahmdAqp1MLw2i6o6Q/KtmNEk8TJspWzXFt6pXAXil9UuGH/voMNZeWlmGMJHuDL6lRYl1d5G7hz+HBfkO+mXLxkaB4GKeRhiU82D5flmVY7XRp/nZ5bDifTFnV7suzViHnvM5YgFwM+OS2RNN/QlavxYL2lE6XRcQCm7pYWrBcuvjLuAbrc+uqW3yz+Ycc4mRFrdpVG/g/S1Mb0Xl/R+kplPS5EWv4I0/l01StA7lGIGuw0Jcd6i4wP+6ibBYRklPrrvHys='

encrypt:
  failOnError: false
  keyStore:
    location: file:${HOME}/keystore.jks
    alias: homepage
    password: ${KEYSTORE_PASSWORD}
    secret: ${KEYSTORE_PASSWORD}