server:
  port: 8888

management:
  context-path: /admin

security:
  user:
    password: '{cipher}AQCB2loFREw8pyHJZT0nYouE0srhJJqdMOeTqcxBmfdGsu3W0Ut8BCbmIsntcDgZUaRDN1hIo+zM2pw7AYkCBWsHrTrmkrGB55hNU4eo4dUy1HjElejg2zMJ60i9BwcSHDlzHxSpS86TLf3tADyNPdvOufkUzqlb3zILWGC/+8cUOAV3bkfe3T96esgHpb2yzExuvL4m45ZArDs6kF8qCTjnzgp5kMPB5PD7cGBspolSzy6YpuH8icMwWpy73u36/0W9bKVGAIodpAouA8n/h0OqbL1/vMJsydYPVlr2WNN6JqRNatGkXHAlVdzwGCkoP5r+Kz6RZpcFf7sIuLRCQ3TABpV/6D24j5yN+8BCqYQejnm7FmNVtA6RHM6I57UyFUc='
      
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  password: '{cipher}AQCp5ZjbYH7zgAJbnDHQQostob3aU+mTPYq90uBdJsYV8YTqLgk+jnnAh3EYZXu66fdLC2TbO9reWwM8GFNhWg4vcX/RdUFd86mcqOTbuhVISGPhzF5hmtu0w8LM9pZY7RoKvaLBaxI5y0LpBx2P8jj5bjdDPDQqvrDrzKJkrxj7WSmU7AE0F6ulB+sHaJu7Oc1XUpNlwNRz2LOyCez5FMfeltbxAzebQr17A6EFe2BqSD6U45sPRs6uLyBD1zg5s6l9adaL1phv77IyF9Ho7btVFAKU3EJijNOdneqz5lAgHeN8f4tnQi9bIZ9Jh7rQHNwPhrhyta3oMU2503KERGRZdpLn0jJNblLZ/0kHDjjzQZN9wCILGiaLWhiWUPzdI/g='
  client:
    serviceUrl:
      defaultZone: ${SPRING_CLOUD_EUREKA_PROTOCOL}://${SPRING_CLOUD_EUREKA_USER}:${eureka.password}@${SPRING_CLOUD_EUREKA_URI}:${SPRING_CLOUD_EUREKA_PORT}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maximilianwollnik/config-repo
          username: maximilianwollnik
          password: '{cipher}AQBMUA9LDqt3LK5iyNs9WPJkXZIRYYljV31myRWCyFKa9ZrE4PEu7Eh/e0B+mv5ogx+GR+WsKk3sRSlH7Tz7PrhBWuKdXwjalDJATFo1HpsveHsowmdY24oTrTpHsXAjEMqMLrl5HZR/AhwBNW9V1A1RBXF0GYVur7gn4A1C3cSKoUdhTRPLSzo0uhrauKSIOTnTcbkYPMNreLnMRPvRRvAgJDKU+yKSVfooEObhX+LcyxqLsyX/PGAtxUw4AT4FRVS71RfYpqgh1Tk6Mb2dR28tHZkcVfyMi6+IXUHEBnmn9G8s7GSdgq9JMSIRjupbXkv1574uku2VtdauspY/Is4WnZmW24PQHkyowll2NmgeQBwGhr1bO0HSVCf+wdYDdQM='
